#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -r n
#PBS -q damp
#PBS -m e
#PBS -j oe
#PBS -l mem=64000MB
#PBS -l walltime=90000000
#PBS -l cput=900000000
#PBS -N pce-example-gopt-pop


echo $PBS_JOBID >jobid
cd $PBS_O_WORKDIR


/usr/local/bin/g09d01-bipbip-intel pce-example-gopt-pop.gjf
